name: DesigniteJava code quality

on:
push:
    branches: [ main ]
pull_request:
    branches: [ main ]

jobs:
build:
    runs-on: ubuntu-latest
    steps:
    - name: DesigniteJava_action
    uses: DesigniteTools/DJAction@v2.0.0
    with:
        PAT: ${{ secrets.PAT }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        API_KEY: ${{ secrets.API_KEY }}
